import pandas as pd

sample_data = pd.DataFrame([
    {
        "material_number": "MAT001",
        "material_description": "Widget A",
        "material_group": "Electronics",
        "base_uom": "pcs",
        "sales_uom": "box",
        "packing_unit": "Box",
        "total_quantity": 100,
        "weight": 25.5,
        "weight_unit": "kg",
        "volume": 0.1,
        "volume_unit": "m3",
        "customs_tariff_number": "12345678",
        "country_of_origin": "Germany",
        "ROHS": "Yes",
        "REACH": "Yes",
        "manufacturer": "ABC Corp",
        "manufacturer_part_number": "ABC123",
        "shelf_life": 365,
        "storage_location": "WH01",
        "gross_weight": 27.0,
        "net_weight": 25.0,
        "batch_number": "BATCH01",
        "quality_inspection_status": "Pass",
        "price": 15.00,
    },
    {
        "material_number": "MAT002",
        "material_description": "Widget B",
        "material_group": "Hardware",
        "base_uom": "pcs",
        "sales_uom": "pcs",
        "packing_unit": "Carton",
        "total_quantity": 50,
        "weight": 12.3,
        "weight_unit": "kg",
        "volume": 0.05,
        "volume_unit": "m3",
        "customs_tariff_number": "87654321",
        "country_of_origin": "France",
        "ROHS": "No",
        "REACH": "Yes",
        "manufacturer": "XYZ Inc",
        "manufacturer_part_number": "XYZ789",
        "shelf_life": 180,
        "storage_location": "WH02",
        "gross_weight": 13.0,
        "net_weight": 12.0,
        "batch_number": "BATCH02",
        "quality_inspection_status": "Pass",
        "price": 12.50,
    },
    {
        "material_number": "MAT003",
        "material_description": "Gadget C",
        "material_group": "Electronics",
        "base_uom": "pcs",
        "sales_uom": "pcs",
        "packing_unit": "Pallet",
        "total_quantity": 200,
        "weight": 150,
        "weight_unit": "kg",
        "volume": 0.5,
        "volume_unit": "m3",
        "customs_tariff_number": "23456789",
        "country_of_origin": "Italy",
        "ROHS": "Yes",
        "REACH": "No",
        "manufacturer": "DEF Ltd",
        "manufacturer_part_number": "DEF456",
        "shelf_life": 730,
        "storage_location": "WH03",
        "gross_weight": 155.0,
        "net_weight": 150.0,
        "batch_number": "BATCH03",
        "quality_inspection_status": "Fail",
        "price": 50.00,
    }
])